"""Tk popup for exploring synthesized components and local connectivity."""

from __future__ import annotations

from collections import Counter
from pathlib import Path
import tkinter as tk
from tkinter import ttk
from typing import Callable

from ide.netlist_graph import NetConnection, NetlistGraph


CATEGORY_ORDER = (
    "Inputs", "I/O", "Logic", "Sequential", "Memory",
    "Clock/reset", "Constants", "Other", "Outputs",
)


class NetlistViewer:
    """Searchable synthesized component list plus readable graph projections."""

    def __init__(
        self,
        parent: tk.Misc,
        graph: NetlistGraph,
        colors: dict[str, str],
        icons: dict[str, tk.PhotoImage],
        open_source: Callable[[Path, int], None],
    ):
        self.graph = graph
        self.colors = colors
        self.icons = icons
        self.open_source = open_source
        self.zoom = 1.0
        self.current_cell: str | None = None
        self.tree_cells: dict[str, str] = {}
        self.cell_tree_items: dict[str, str] = {}

        self.window = tk.Toplevel(parent)
        self.window.title("Synthesized netlist viewer")
        self.window.geometry("1240x760")
        self.window.minsize(900, 580)
        self.window.configure(bg=colors["bg"])
        self.window.transient(parent)
        self._build()
        self._populate_cells()
        self.draw_overview()

    def _build(self) -> None:
        header = ttk.Frame(self.window, style="Top.TFrame", padding=(20, 15, 20, 10))
        header.pack(fill="x")
        title_row = ttk.Frame(header, style="Top.TFrame")
        title_row.pack(fill="x")
        ttk.Label(
            title_row, image=self.icons["dashboard"], text="  Synthesized netlist",
            compound="left", style="Title.TLabel",
        ).pack(side="left")
        ttk.Button(title_row, text="Close", command=self.window.destroy).pack(side="right")
        ttk.Label(
            header,
            text=(
                f"{self.graph.module_name}  •  {len(self.graph.cells):,} cells  •  "
                f"{len(self.graph.connections):,} connections  •  generated by "
                f"{self._short(self.graph.creator.split(' (git sha1')[0], 55)}"
            ),
            style="Status.TLabel",
        ).pack(anchor="w", pady=(4, 0))

        toolbar = ttk.Frame(self.window, padding=(14, 8))
        toolbar.pack(fill="x")
        ttk.Label(toolbar, image=self.icons["search"]).pack(side="left", padx=(0, 5))
        self.search_var = tk.StringVar()
        self.search_var.trace_add("write", lambda *_args: self._populate_cells())
        search = ttk.Entry(toolbar, textvariable=self.search_var, width=28)
        search.pack(side="left", padx=(0, 8))
        self.type_var = tk.StringVar(value="All types")
        types = ["All types"] + sorted(self.graph.type_counts, key=str.lower)
        type_filter = ttk.Combobox(
            toolbar, textvariable=self.type_var, values=types, state="readonly", width=18,
        )
        type_filter.pack(side="left", padx=(0, 12))
        type_filter.bind("<<ComboboxSelected>>", lambda _event: self._populate_cells())
        ttk.Button(toolbar, text="Overview", command=self.draw_overview).pack(side="left")
        ttk.Button(toolbar, text="−", width=3, command=lambda: self._change_zoom(-0.15)).pack(side="right")
        self.zoom_text = tk.StringVar(value="100%")
        ttk.Label(toolbar, textvariable=self.zoom_text, width=6, anchor="center").pack(side="right")
        ttk.Button(toolbar, text="+", width=3, command=lambda: self._change_zoom(0.15)).pack(side="right")
        ttk.Button(toolbar, text="Fit", command=self._fit).pack(side="right", padx=(0, 8))

        main = ttk.Panedwindow(self.window, orient="horizontal")
        main.pack(fill="both", expand=True, padx=12, pady=(0, 12))
        left = ttk.Frame(main, style="Card.TFrame", padding=6)
        right = ttk.Frame(main, style="Card.TFrame")
        main.add(left, weight=2)
        main.add(right, weight=5)

        list_header = ttk.Frame(left, padding=(4, 3, 4, 7))
        list_header.pack(fill="x")
        ttk.Label(list_header, text="Components", font=("Segoe UI Semibold", 11)).pack(side="left")
        self.list_status = tk.StringVar()
        ttk.Label(list_header, textvariable=self.list_status, style="Muted.TLabel").pack(side="right")
        tree_frame = ttk.Frame(left)
        tree_frame.pack(fill="both", expand=True)
        self.tree = ttk.Treeview(
            tree_frame, columns=("type", "category", "source"), show="tree headings", selectmode="browse",
        )
        self.tree.heading("#0", text="Cell")
        self.tree.heading("type", text="Type")
        self.tree.heading("category", text="Group")
        self.tree.heading("source", text="RTL")
        self.tree.column("#0", width=190, stretch=True)
        self.tree.column("type", width=90, stretch=False)
        self.tree.column("category", width=85, stretch=False)
        self.tree.column("source", width=105, stretch=False)
        tree_scroll = ttk.Scrollbar(tree_frame, orient="vertical", command=self.tree.yview)
        self.tree.configure(yscrollcommand=tree_scroll.set)
        self.tree.pack(side="left", fill="both", expand=True)
        tree_scroll.pack(side="right", fill="y")
        self.tree.bind("<<TreeviewSelect>>", self._tree_selected)
        self.tree.bind("<Double-1>", lambda _event: self._open_current_source())
        list_actions = ttk.Frame(left, padding=(3, 7, 3, 2))
        list_actions.pack(fill="x")
        self.open_button = ttk.Button(list_actions, text="Open RTL source", command=self._open_current_source)
        self.open_button.pack(side="left")
        self.open_button.configure(state="disabled")
        ttk.Label(list_actions, text="Double-click a cell to navigate", style="Muted.TLabel").pack(side="right")

        canvas_header = ttk.Frame(right, padding=(10, 7))
        canvas_header.pack(fill="x")
        self.view_title = tk.StringVar(value="Categorized overview")
        ttk.Label(canvas_header, textvariable=self.view_title, font=("Segoe UI Semibold", 11)).pack(side="left")
        ttk.Label(
            canvas_header, text="Select a component to see one-hop connectivity",
            style="Muted.TLabel",
        ).pack(side="right")
        canvas_frame = tk.Frame(
            right, bg=self.colors["editor"], highlightthickness=1,
            highlightbackground=self.colors["border_soft"],
        )
        canvas_frame.pack(fill="both", expand=True)
        self.canvas = tk.Canvas(
            canvas_frame, bg=self.colors["editor"], highlightthickness=0,
            xscrollincrement=20, yscrollincrement=20,
        )
        x_scroll = ttk.Scrollbar(canvas_frame, orient="horizontal", command=self.canvas.xview)
        y_scroll = ttk.Scrollbar(canvas_frame, orient="vertical", command=self.canvas.yview)
        self.canvas.configure(xscrollcommand=x_scroll.set, yscrollcommand=y_scroll.set)
        self.canvas.grid(row=0, column=0, sticky="nsew")
        y_scroll.grid(row=0, column=1, sticky="ns")
        x_scroll.grid(row=1, column=0, sticky="ew")
        canvas_frame.rowconfigure(0, weight=1)
        canvas_frame.columnconfigure(0, weight=1)
        self.canvas.bind("<Control-MouseWheel>", self._wheel_zoom)
        self.canvas.bind("<ButtonPress-2>", self._pan_start)
        self.canvas.bind("<B2-Motion>", self._pan_move)
        self.canvas.bind("<ButtonPress-3>", self._pan_start)
        self.canvas.bind("<B3-Motion>", self._pan_move)

        detail = ttk.Frame(right, padding=(10, 8))
        detail.pack(fill="x")
        self.detail_text = tk.StringVar(value="Overview groups synthesized primitives by purpose; edge labels are connection counts.")
        ttk.Label(detail, textvariable=self.detail_text, style="Muted.TLabel", wraplength=760).pack(anchor="w")

    def _populate_cells(self) -> None:
        if not hasattr(self, "tree"):
            return
        query = self.search_var.get().strip().lower()
        selected_type = self.type_var.get()
        selected_name = self.current_cell
        self.tree.delete(*self.tree.get_children())
        self.tree_cells.clear()
        self.cell_tree_items.clear()
        matches = [
            cell for cell in self.graph.cells.values()
            if (selected_type == "All types" or cell.cell_type == selected_type)
            and (
                not query
                or query in cell.name.lower()
                or query in cell.cell_type.lower()
                or query in cell.category.lower()
            )
        ]
        matches.sort(key=lambda cell: (cell.category, cell.cell_type.lower(), cell.name.lower()))
        for cell in matches[:5000]:
            source = f"{cell.source.path.name}:{cell.source.line}" if cell.source else "—"
            item = self.tree.insert(
                "", "end", text=self._short(cell.name, 42),
                values=(cell.cell_type, cell.category, source),
            )
            self.tree_cells[item] = cell.name
            self.cell_tree_items[cell.name] = item
        suffix = "" if len(matches) <= 5000 else " (first 5,000)"
        self.list_status.set(f"{len(matches):,}{suffix}")
        if selected_name in self.cell_tree_items:
            item = self.cell_tree_items[selected_name]
            self.tree.selection_set(item)
            self.tree.see(item)

    def _tree_selected(self, _event=None) -> None:
        selected = self.tree.selection()
        if not selected:
            return
        name = self.tree_cells.get(selected[0])
        if name:
            self.draw_neighborhood(name)

    def _open_current_source(self) -> None:
        if not self.current_cell:
            return
        cell = self.graph.cells.get(self.current_cell)
        if cell and cell.source:
            self.open_source(cell.source.path, cell.source.line)

    def _endpoint_category(self, name: str) -> str:
        if name.startswith("port:"):
            port = self.graph.ports.get(name[5:])
            return "Inputs" if port and port.direction == "input" else "Outputs"
        cell = self.graph.cells.get(name)
        return cell.category if cell else "Other"

    def draw_overview(self) -> None:
        self.current_cell = None
        selected = self.tree.selection()
        if selected:
            self.tree.selection_remove(*selected)
        self.open_button.configure(state="disabled")
        self.view_title.set("Categorized synthesized overview")
        self.detail_text.set(
            "This overview stays readable by grouping implementation primitives. Select a component on the left "
            "for its real one-hop fan-in and fan-out."
        )
        counts = self.graph.category_counts
        node_counts = {"Inputs": sum(port.direction == "input" for port in self.graph.ports.values())}
        node_counts.update(counts)
        node_counts["Outputs"] = sum(port.direction == "output" for port in self.graph.ports.values())
        active = [name for name in CATEGORY_ORDER if node_counts.get(name, 0)]
        overview_positions = {
            "Inputs": (95, 250), "I/O": (250, 250),
            "Logic": (430, 75), "Sequential": (430, 180),
            "Memory": (430, 285), "Clock/reset": (430, 390),
            "Constants": (250, 455), "Other": (430, 505),
            "Outputs": (630, 250),
        }
        positions = {name: overview_positions[name] for name in active}
        category_edges: Counter[tuple[str, str]] = Counter()
        for connection in self.graph.connections:
            source = self._endpoint_category(connection.source)
            target = self._endpoint_category(connection.target)
            if source != target and source in positions and target in positions:
                category_edges[(source, target)] += 1
        self.canvas.delete("all")
        for (source, target), count in category_edges.items():
            self._draw_edge(positions[source], positions[target], str(count))
        for name in active:
            self._draw_node(name, positions[name], f"{node_counts[name]:,} item{'s' if node_counts[name] != 1 else ''}")
        self._finish_render()

    def draw_neighborhood(self, name: str) -> None:
        cell = self.graph.cells.get(name)
        if cell is None:
            return
        self.current_cell = name
        self.view_title.set(f"Local connectivity — {self._short(name, 58)}")
        incoming = self.graph.incoming(name)
        outgoing = self.graph.outgoing(name)
        source = f"{cell.source.path.name}:{cell.source.line}" if cell.source else "No RTL source location"
        self.detail_text.set(
            f"{cell.cell_type} • {cell.category} • {source} • "
            f"{len(incoming)} incoming relationship(s) • {len(outgoing)} outgoing relationship(s)"
        )
        self.open_button.configure(state="normal" if cell.source else "disabled")
        self.canvas.delete("all")
        center = (510, 280)
        upstream = self._unique_connections(incoming, "source")
        downstream = self._unique_connections(outgoing, "target")
        visible_upstream = upstream[:12]
        visible_downstream = downstream[:12]
        upstream_positions = self._side_positions(len(visible_upstream), 80)
        downstream_positions = self._side_positions(len(visible_downstream), 940)
        for connection, position in zip(visible_upstream, upstream_positions):
            endpoint = connection.source
            self._draw_edge(position, center, self._net_label(connection))
            self._draw_endpoint(endpoint, position)
        for connection, position in zip(visible_downstream, downstream_positions):
            endpoint = connection.target
            self._draw_edge(center, position, self._net_label(connection))
            self._draw_endpoint(endpoint, position)
        self._draw_node(name, center, cell.cell_type, selected=True, node_name=name)
        if len(upstream) > 12:
            self.canvas.create_text(80, 570, text=f"+ {len(upstream) - 12} more inputs", fill=self.colors["muted"])
        if len(downstream) > 12:
            self.canvas.create_text(940, 570, text=f"+ {len(downstream) - 12} more outputs", fill=self.colors["muted"])
        self._finish_render()

    @staticmethod
    def _unique_connections(connections: list[NetConnection], endpoint: str) -> list[NetConnection]:
        seen: set[str] = set()
        result: list[NetConnection] = []
        for connection in connections:
            value = getattr(connection, endpoint)
            if value not in seen:
                seen.add(value)
                result.append(connection)
        return result

    @staticmethod
    def _side_positions(count: int, x: int) -> list[tuple[int, int]]:
        if count <= 0:
            return []
        spacing = min(82, 480 // max(1, count))
        start = 280 - ((count - 1) * spacing) // 2
        return [(x, start + index * spacing) for index in range(count)]

    def _draw_endpoint(self, name: str, position: tuple[int, int]) -> None:
        if name.startswith("port:"):
            port_name = name[5:]
            port = self.graph.ports.get(port_name)
            subtitle = f"top {port.direction}" if port else "top port"
            self._draw_node(port_name, position, subtitle)
            return
        cell = self.graph.cells.get(name)
        self._draw_node(
            name, position, cell.cell_type if cell else "component",
            node_name=name if cell else None,
        )

    def _draw_node(
        self, title: str, position: tuple[int, int], subtitle: str,
        *, selected: bool = False, node_name: str | None = None,
    ) -> None:
        x, y = position
        width, height = (190, 70) if selected else (170, 62)
        tag = f"netlist_node_{len(self.canvas.find_all())}"
        fill = self.colors["selection"] if selected else self.colors["panel_alt"]
        outline = self.colors["accent"] if selected else self.colors["border"]
        self.canvas.create_rectangle(
            x - width // 2, y - height // 2, x + width // 2, y + height // 2,
            fill=fill, outline=outline, width=2 if selected else 1, tags=(tag,),
        )
        self.canvas.create_text(
            x, y - 9, text=self._short(title, 26), fill=self.colors["text"],
            font=("Segoe UI Semibold", 10), tags=(tag,),
        )
        self.canvas.create_text(
            x, y + 13, text=self._short(subtitle, 26), fill=self.colors["muted"],
            font=("Segoe UI", 9), tags=(tag,),
        )
        if node_name and node_name in self.graph.cells:
            self.canvas.tag_bind(tag, "<Button-1>", lambda _event, value=node_name: self._select_canvas_cell(value))
            self.canvas.tag_bind(tag, "<Enter>", lambda _event: self.canvas.configure(cursor="hand2"))
            self.canvas.tag_bind(tag, "<Leave>", lambda _event: self.canvas.configure(cursor=""))

    def _draw_edge(
        self, source: tuple[int, int], target: tuple[int, int], label: str,
    ) -> None:
        sx, sy = source
        tx, ty = target
        direction = 1 if tx >= sx else -1
        start_x = sx + 88 * direction
        end_x = tx - 88 * direction
        middle_x = (start_x + end_x) / 2
        self.canvas.create_line(
            start_x, sy, middle_x, sy, middle_x, ty, end_x, ty,
            fill=self.colors["border"], width=1, arrow="last", smooth=True,
        )
        if label:
            self.canvas.create_text(
                middle_x + 3, (sy + ty) / 2, text=self._short(label, 24),
                fill=self.colors["muted_2"], font=("Segoe UI", 8), anchor="w",
            )

    def _select_canvas_cell(self, name: str) -> None:
        self.current_cell = name
        item = self.cell_tree_items.get(name)
        if item:
            self.tree.selection_set(item)
            self.tree.focus(item)
            self.tree.see(item)
        else:
            self.draw_neighborhood(name)

    @staticmethod
    def _net_label(connection: NetConnection) -> str:
        value = ", ".join(connection.nets[:2])
        if len(connection.nets) > 2:
            value += f" +{len(connection.nets) - 2}"
        return value

    @staticmethod
    def _short(value: str, limit: int) -> str:
        return value if len(value) <= limit else value[:limit - 1] + "…"

    def _finish_render(self) -> None:
        if self.zoom != 1.0:
            self.canvas.scale("all", 0, 0, self.zoom, self.zoom)
        bounds = self.canvas.bbox("all") or (0, 0, 1100, 620)
        self.canvas.configure(scrollregion=(bounds[0] - 50, bounds[1] - 50, bounds[2] + 50, bounds[3] + 50))
        self.canvas.xview_moveto(0)
        self.canvas.yview_moveto(0)
        self.zoom_text.set(f"{int(self.zoom * 100)}%")

    def _change_zoom(self, delta: float) -> None:
        self.zoom = max(0.5, min(2.0, round(self.zoom + delta, 2)))
        if self.current_cell:
            self.draw_neighborhood(self.current_cell)
        else:
            self.draw_overview()

    def _fit(self) -> None:
        self.zoom = 0.75 if self.current_cell is None else 0.9
        if self.current_cell:
            self.draw_neighborhood(self.current_cell)
        else:
            self.draw_overview()

    def _wheel_zoom(self, event) -> str:
        self._change_zoom(0.1 if event.delta > 0 else -0.1)
        return "break"

    def _pan_start(self, event) -> None:
        self.canvas.scan_mark(event.x, event.y)

    def _pan_move(self, event) -> None:
        self.canvas.scan_dragto(event.x, event.y, gain=1)


def open_netlist_viewer(
    parent: tk.Misc,
    graph: NetlistGraph,
    colors: dict[str, str],
    icons: dict[str, tk.PhotoImage],
    open_source: Callable[[Path, int], None],
) -> tk.Toplevel:
    return NetlistViewer(parent, graph, colors, icons, open_source).window
